- name: "ensure apache2 is installed"
  apt:
    pkg: apache2
- name: copy template index 
  template: 
    src: index.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644

- name: "Copiar fichero al servidor remoto"
  copy:
    src: fichero.html
    dest: /var/www/html/fichero.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: "Copiar fichero de configuracion"
  copy:
    src: etc/apache2/ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'

- name: "Cambiar el puerto por defecto, por el puerto 81 y reiniciar el servicio"
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80 8081" line="Listen 81 8081" state=present
  notify:
    - restart apache2
